require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.1

RSpec/AnyInstance:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Bundler/DuplicatedGem:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Enabled: false